import fs from 'fs';
import path from 'path';
import { MasterTimeline } from '../types/index.js';
import { JobManager } from '../core/job.js';

export class CaptionEngine {
  constructor(private job: JobManager) {}

  public run(timeline: MasterTimeline): string {
    this.job.status.update({
      current_step: 'CAPTIONS',
      message: 'Generating cinematic ASS animated subtitles...'
    });

    const assPath = path.join(this.job.dirs.captionsDir, 'captions.ass');

    // Horror ASS header with cinematic typography and drop shadow
    let assContent = `[Script Info]
; Script generated by Nightfall AI Horror Engine
Title: Cinematic Horror Captions
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: HorrorNormal,Arial,46,&H00FFFFFF,&H000000FF,&H00000000,&H90000000,-1,0,0,0,100,100,1,0,1,3.5,2,2,60,60,110,1
Style: HorrorAccent,Arial,50,&H002020FF,&H000000FF,&H00000000,&H90000000,-1,0,0,0,104,104,1,0,1,4.0,3,2,60,60,110,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

    // Process narration segments and slice them into cinematic phrase beats (4-7 words per line)
    for (const segment of timeline.narration_segments) {
      const words = segment.text.trim().split(/\s+/);
      const totalWords = words.length;
      if (totalWords === 0) continue;

      const segDuration = segment.end_time - segment.start_time;
      const wordsPerCard = 5;
      const numCards = Math.ceil(totalWords / wordsPerCard);
      const cardDuration = segDuration / numCards;

      for (let c = 0; c < numCards; c++) {
        const cardWords = words.slice(c * wordsPerCard, (c + 1) * wordsPerCard);
        const cardStart = segment.start_time + c * cardDuration;
        const cardEnd = Math.min(segment.end_time, cardStart + cardDuration);

        const startTimecode = this.formatTimecode(cardStart);
        const endTimecode = this.formatTimecode(cardEnd);

        // Highlight suspenseful keywords with crimson glow
        const highlightedText = cardWords
          .map(w => {
            const clean = w.toLowerCase().replace(/[^a-z]/g, '');
            if (['dead', 'death', 'blood', 'severed', 'screamed', 'night', 'static', 'whisper', 'door', 'dark', 'alone', 'cold'].includes(clean)) {
              return `{\\c&H3030FF&\\b1}${w}{\\rHorrorNormal}`;
            }
            return w;
          })
          .join(' ');

        // Subtle fade-in and fade-out animation
        const lineText = `{\\fad(80,80)}${highlightedText}`;
        assContent += `Dialogue: 0,${startTimecode},${endTimecode},HorrorNormal,,0,0,0,,${lineText}\n`;
      }
    }

    fs.writeFileSync(assPath, assContent, 'utf8');
    this.job.logger.info('CAPTIONS', `Cinematic ASS captions generated at: ${assPath}`);
    return assPath;
  }

  private formatTimecode(seconds: number): string {
    const h = Math.floor(seconds / 3600);
    const m = Math.floor((seconds % 3600) / 60);
    const s = Math.floor(seconds % 60);
    const ms = Math.floor((seconds % 1) * 100);

    const mStr = String(m).padStart(2, '0');
    const sStr = String(s).padStart(2, '0');
    const msStr = String(ms).padStart(2, '0');

    return `${h}:${mStr}:${sStr}.${msStr}`;
  }
}
